definitions:
  err_code.Error:
    properties:
      code:
        description: error code
        type: integer
      details:
        description: error detail info
        items:
          type: string
        type: array
      msg:
        description: error description
        type: string
    type: object
  model.Note:
    properties:
      content:
        type: string
      created_on:
        type: string
      id:
        type: integer
    type: object
  service.NoteDisplay:
    properties:
      content:
        type: string
      time:
        description: 格式化为的输出时间
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      produces:
      - text/html
      responses:
        "200":
          description: 展示注册界面
      summary: 向用户展示文件上传界面
      tags:
      - Index
  /api/notes:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: 留言内容
        in: body
        name: note_content
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_code.Error'
        "401":
          description: 需要登录后才能使用 api 操作
          schema:
            $ref: '#/definitions/err_code.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_code.Error'
      summary: 创建一条留言
      tags:
      - Note
  /api/notes/:
    get:
      parameters:
      - description: 限制返回的数量
        in: query
        maximum: 10
        minimum: 5
        name: limit
        type: integer
      - description: 记录上一次返回的最大id，用于实现数据库翻页
        in: query
        minimum: 0
        name: min_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.NoteDisplay'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_code.Error'
        "401":
          description: 需要登录后才能使用 api 操作
          schema:
            $ref: '#/definitions/err_code.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_code.Error'
      summary: 获得留言列表
      tags:
      - Note
  /api/notes/{id}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: url结尾必须为int类型
          schema:
            $ref: '#/definitions/err_code.Error'
        "401":
          description: 需要登录后才能使用 api 操作
          schema:
            $ref: '#/definitions/err_code.Error'
        "500":
          description: 可能为数据库查询出现问题
          schema:
            $ref: '#/definitions/err_code.Error'
      summary: 删除一条留言
      tags:
      - Note
    get:
      parameters:
      - description: 留言id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Note'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_code.Error'
        "401":
          description: 需要登录后才能使用 api 操作
          schema:
            $ref: '#/definitions/err_code.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_code.Error'
      summary: 更新一条留言
      tags:
      - Note
    put:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: 留言id
        in: path
        name: id
        required: true
        type: string
      - description: 留言内容
        in: body
        name: note_content
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_code.Error'
        "401":
          description: 需要登录后才能使用 api 操作
          schema:
            $ref: '#/definitions/err_code.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_code.Error'
      summary: 更新一条留言
      tags:
      - Note
  /auth:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: 用户名称
        in: body
        maxLength: 20
        name: user
        required: true
        schema:
          type: string
      - description: 用户密码
        in: body
        maxLength: 20
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_code.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err_code.Error'
      summary: 根据用户所填写的信息来对api接口进行授权
      tags:
      - Auth
  /login:
    get:
      produces:
      - text/html
      responses:
        "200":
          description: 展示注册界面
      summary: 向用户展示注册界面
      tags:
      - Auth
  /register:
    get:
      produces:
      - text/html
      responses:
        "200":
          description: 展示登录界面
      summary: 向用户展示注册界面
      tags:
      - Auth
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: 用户名称
        in: body
        maxLength: 20
        name: user
        required: true
        schema:
          type: string
      - description: 用户密码
        in: body
        maxLength: 20
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_code.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err_code.Error'
      summary: 根据用户所填写的信息进行注册操作
      tags:
      - Auth
  /upload:
    get:
      produces:
      - text/html
      responses:
        "200":
          description: 展示注册界面
      summary: 向用户展示文件上传界面
      tags:
      - File
swagger: "2.0"
